FROM adoptopenjdk:11-jre-hotspot
COPY *.jar /rvc-captcha.jar


ARG SERVER_PORT
ARG ACTIVE
ARG UNIQUE_ID
ARG JASYPT_PASSWORD

ARG MYSQL_ADDR
ARG MYSQL_USERNAME
ARG MYSQL_PASSWORD

ARG REDIS_ADDR
ARG REDIS_PORT
ARG REDIS_PWD

ARG NACOS_SERVER_ADDR
ARG NACOS_SERVER_USER
ARG NACOS_SERVER_PASSWORD

ARG MQ_ADDR
ARG MQ_PORT
ARG MQ_USERNAME
ARG MQ_PWD

ENV SERVER_PORT=${SERVER_PORT}
ENV UNIQUE_ID=${UNIQUE_ID}
ENV JASYPT_PASSWORD = ${JASYPT_PASSWORD}
EXPOSE ${SERVER_PORT}

ENTRYPOINT ["java","-jar","/rvc-captcha.jar"]

#<Auto> -e:test -type:single -m:rvc-captcha -v:1.0.2 -rp:8080 -de:<-e ACTIVE=test -e SERVER_PORT=8080>
